// using System.CommandLine.DragonFruit;

namespace Regata.Utilities.UpdateManager
{
  // TODO: implement update function
  // TODO: add tests
  // TODO: add roslyn static analyzer
  // FIXME: icon via csproj doesn't include into update, i.e. after build exe file with ico but after setup not
  // FIXME: System.CommandLine.DragonFruit gives:
  /*
  Build FAILED.

obj\Debug\netcoreapp3.1\RegataUpdateManager.Program.g.cs(6,24): error CS0101: The namespace '<global namespace>' already contains a definition for 'AutoGeneratedProgram' [D:\GoogleDrive\Job\flnp\dev\RegataUpdateManager\RegataUpdateManager.csproj]
obj\Debug\netcoreapp3.1\RegataUpdateManager.Program.g.cs(8,41): error CS0111: Type 'AutoGeneratedProgram' already defines a member called 'Main' with the same parameter types [D:\GoogleDrive\Job\flnp\dev\RegataUpdateManager\RegataUpdateManager.csproj]
  */

  class Program
  {
    /// <summary>
    /// Creates files for release using Squirrel.Windows and upload them to GitHub release page.
    /// All information (Repository, Versions, Title, Description) should be specified in csproj file.
    /// Example:
    /// UpdateManager test.csproj
    /// will seek first csproj file in the current directory
    /// after that will generate release files from the package in bin\Release
    /// The name of package is 'PackageId.Version.nupkg'
    /// </summary>
    /// <param name="fileProject">Path of csproj file. By default first csproj file in the current directory.</param>
    static void Main(string[] args)
    {
      var upd = new UpdateManager(args[0]);
      upd.CreateRelease();
      upd.UploadReleaseToGithub().Wait();
    }
  }
}
